// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCall = `-- name: CreateCall :one
INSERT INTO calls(channel_id)
VALUES ($1)
RETURNING id, channel_id, dm_id, thread_msg_id, started_by, status, started_at, ended_at, duration_sec
`

func (q *Queries) CreateCall(ctx context.Context, channelID pgtype.UUID) (Call, error) {
	row := q.db.QueryRow(ctx, createCall, channelID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.DmID,
		&i.ThreadMsgID,
		&i.StartedBy,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSec,
	)
	return i, err
}

const createCallParticipants = `-- name: CreateCallParticipants :one
INSERT INTO call_participants(call_id,user_id)
VALUES ($1,$2)
RETURNING call_id, user_id, joined_at, left_at
`

type CreateCallParticipantsParams struct {
	CallID pgtype.UUID `json:"call_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateCallParticipants(ctx context.Context, arg CreateCallParticipantsParams) (CallParticipant, error) {
	row := q.db.QueryRow(ctx, createCallParticipants, arg.CallID, arg.UserID)
	var i CallParticipant
	err := row.Scan(
		&i.CallID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const createCallSummaries = `-- name: CreateCallSummaries :one
INSERT INTO call_summaries(call_id,transcript,summary)
VALUES ($1,$2,$3)
RETURNING id, call_id, transcript, summary, msg_id, created_at
`

type CreateCallSummariesParams struct {
	CallID     pgtype.UUID `json:"call_id"`
	Transcript pgtype.Text `json:"transcript"`
	Summary    pgtype.Text `json:"summary"`
}

func (q *Queries) CreateCallSummaries(ctx context.Context, arg CreateCallSummariesParams) (CallSummary, error) {
	row := q.db.QueryRow(ctx, createCallSummaries, arg.CallID, arg.Transcript, arg.Summary)
	var i CallSummary
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.Transcript,
		&i.Summary,
		&i.MsgID,
		&i.CreatedAt,
	)
	return i, err
}
