// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels(name,is_private,created_by)
VALUES ($1,$2,$3)
RETURNING id, name, is_private, created_by, created_at
`

type CreateChannelParams struct {
	Name      string      `json:"name"`
	IsPrivate pgtype.Bool `json:"is_private"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.Name, arg.IsPrivate, arg.CreatedBy)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelById = `-- name: GetChannelById :one
SELECT id, name, is_private, created_by, created_at FROM channels
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetChannelById(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelById, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChannels = `-- name: GetChannels :many
SELECT id, name, is_private, created_by, created_at FROM channels
WHERE is_private = false
`

func (q *Queries) GetChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinChannel = `-- name: JoinChannel :exec
INSERT INTO channel_members(channel_id,user_id)
VALUES ($1,$2)
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type JoinChannelParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) JoinChannel(ctx context.Context, arg JoinChannelParams) error {
	_, err := q.db.Exec(ctx, joinChannel, arg.ChannelID, arg.UserID)
	return err
}

const leaveChannel = `-- name: LeaveChannel :exec
DELETE FROM channel_members
WHERE channel_id = $1 AND user_id = $2
`

type LeaveChannelParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LeaveChannel(ctx context.Context, arg LeaveChannelParams) error {
	_, err := q.db.Exec(ctx, leaveChannel, arg.ChannelID, arg.UserID)
	return err
}
