// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels(name,channel_type,created_by,workspace_id)
VALUES ($1,$2,$3,$4)
RETURNING id, workspace_id, name, channel_type, created_by, created_at
`

type CreateChannelParams struct {
	Name        string      `json:"name"`
	ChannelType string      `json:"channel_type"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.ChannelType,
		arg.CreatedBy,
		arg.WorkspaceID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ChannelType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelById = `-- name: GetChannelById :one
SELECT id, workspace_id, name, channel_type, created_by, created_at FROM channels
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetChannelById(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelById, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ChannelType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelMembers = `-- name: GetChannelMembers :many
SELECT u.id, u.username, u.email, u.avatar_url
FROM channel_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.channel_id = $1
`

type GetChannelMembersRow struct {
	ID        pgtype.UUID `json:"id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) GetChannelMembers(ctx context.Context, channelID pgtype.UUID) ([]GetChannelMembersRow, error) {
	rows, err := q.db.Query(ctx, getChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelMembersRow
	for rows.Next() {
		var i GetChannelMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannels = `-- name: GetChannels :many
SELECT id, workspace_id, name, channel_type, created_by, created_at FROM channels
WHERE is_private = false
`

func (q *Queries) GetChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ChannelType,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelsByWorkspace = `-- name: GetChannelsByWorkspace :many
SELECT c.id, c.workspace_id, c.name, c.channel_type, c.created_by, c.created_at FROM channels c
WHERE c.workspace_id = $1
AND (
    c.channel_type = 'public'
    OR EXISTS (
        SELECT 1 FROM channel_members cm
        WHERE cm.channel_id = c.id AND cm.user_id = $2
    )
)
ORDER BY c.created_at ASC
`

type GetChannelsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetChannelsByWorkspace(ctx context.Context, arg GetChannelsByWorkspaceParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getChannelsByWorkspace, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ChannelType,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS (
    SELECT 1
    FROM channel_members
    WHERE channel_id = $1
      AND user_id = $2
)
`

type IsChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMember, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const joinChannel = `-- name: JoinChannel :exec
INSERT INTO channel_members(channel_id,user_id)
VALUES ($1,$2)
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type JoinChannelParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) JoinChannel(ctx context.Context, arg JoinChannelParams) error {
	_, err := q.db.Exec(ctx, joinChannel, arg.ChannelID, arg.UserID)
	return err
}

const leaveChannel = `-- name: LeaveChannel :exec
DELETE FROM channel_members
WHERE channel_id = $1 AND user_id = $2
`

type LeaveChannelParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LeaveChannel(ctx context.Context, arg LeaveChannelParams) error {
	_, err := q.db.Exec(ctx, leaveChannel, arg.ChannelID, arg.UserID)
	return err
}
