// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages(channel_id,sender_id,content,parent_id,msg_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, channel_id, sender_id, content, parent_id, msg_type, created_at, edited_at
`

type CreateMessageParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	SenderID  pgtype.UUID `json:"sender_id"`
	Content   string      `json:"content"`
	ParentID  pgtype.UUID `json:"parent_id"`
	MsgType   pgtype.Text `json:"msg_type"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChannelID,
		arg.SenderID,
		arg.Content,
		arg.ParentID,
		arg.MsgType,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.Content,
		&i.ParentID,
		&i.MsgType,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1 AND sender_id = $2
`

type DeleteMessageParams struct {
	ID       pgtype.UUID `json:"id"`
	SenderID pgtype.UUID `json:"sender_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.SenderID)
	return err
}

const editMessage = `-- name: EditMessage :one
UPDATE messages
SET content = $2, edited_at = NOW()
WHERE id = $1 AND sender_id = $3
RETURNING id, channel_id, sender_id, content, parent_id, msg_type, created_at, edited_at
`

type EditMessageParams struct {
	ID       pgtype.UUID `json:"id"`
	Content  string      `json:"content"`
	SenderID pgtype.UUID `json:"sender_id"`
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, editMessage, arg.ID, arg.Content, arg.SenderID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.Content,
		&i.ParentID,
		&i.MsgType,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getChannelMessages = `-- name: GetChannelMessages :many
SELECT
    m.id,
    m.channel_id,
    m.sender_id,
    m.content,
    m.parent_id,
    m.msg_type,
    m.created_at,
    m.edited_at,
    u.username AS sender_username,
    u.avatar_url AS sender_avatar
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.channel_id = $1
AND m.parent_id IS NULL
AND ($2::timestamptz IS NULL OR m.created_at < $2)
ORDER BY m.created_at DESC
LIMIT $3
`

type GetChannelMessagesParams struct {
	ChannelID pgtype.UUID        `json:"channel_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Limit     int32              `json:"limit"`
}

type GetChannelMessagesRow struct {
	ID             pgtype.UUID        `json:"id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	Content        string             `json:"content"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	MsgType        pgtype.Text        `json:"msg_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	SenderUsername string             `json:"sender_username"`
	SenderAvatar   pgtype.Text        `json:"sender_avatar"`
}

func (q *Queries) GetChannelMessages(ctx context.Context, arg GetChannelMessagesParams) ([]GetChannelMessagesRow, error) {
	rows, err := q.db.Query(ctx, getChannelMessages, arg.ChannelID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelMessagesRow
	for rows.Next() {
		var i GetChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderID,
			&i.Content,
			&i.ParentID,
			&i.MsgType,
			&i.CreatedAt,
			&i.EditedAt,
			&i.SenderUsername,
			&i.SenderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, channel_id, sender_id, content, parent_id, msg_type, created_at, edited_at from messages WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.Content,
		&i.ParentID,
		&i.MsgType,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getThreadMessages = `-- name: GetThreadMessages :many
SELECT
    m.id,
    m.channel_id,
    m.sender_id,
    m.content,
    m.parent_id,
    m.msg_type,
    m.created_at,
    m.edited_at,
    u.username AS sender_username,
    u.avatar_url AS sender_avatar 
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.parent_id = $1
ORDER BY m.created_at ASC
`

type GetThreadMessagesRow struct {
	ID             pgtype.UUID        `json:"id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	Content        string             `json:"content"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	MsgType        pgtype.Text        `json:"msg_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	SenderUsername string             `json:"sender_username"`
	SenderAvatar   pgtype.Text        `json:"sender_avatar"`
}

func (q *Queries) GetThreadMessages(ctx context.Context, parentID pgtype.UUID) ([]GetThreadMessagesRow, error) {
	rows, err := q.db.Query(ctx, getThreadMessages, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreadMessagesRow
	for rows.Next() {
		var i GetThreadMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderID,
			&i.Content,
			&i.ParentID,
			&i.MsgType,
			&i.CreatedAt,
			&i.EditedAt,
			&i.SenderUsername,
			&i.SenderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
