// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Call struct {
	ID          pgtype.UUID        `json:"id"`
	ChannelID   pgtype.UUID        `json:"channel_id"`
	ThreadMsgID pgtype.UUID        `json:"thread_msg_id"`
	StartedBy   pgtype.UUID        `json:"started_by"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
	DurationSec pgtype.Int4        `json:"duration_sec"`
}

type CallParticipant struct {
	CallID   pgtype.UUID        `json:"call_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
	LeftAt   pgtype.Timestamptz `json:"left_at"`
}

type CallSummary struct {
	ID         pgtype.UUID        `json:"id"`
	CallID     pgtype.UUID        `json:"call_id"`
	Transcript pgtype.Text        `json:"transcript"`
	Summary    pgtype.Text        `json:"summary"`
	MsgID      pgtype.UUID        `json:"msg_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Channel struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	IsPrivate pgtype.Bool        `json:"is_private"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChannelMember struct {
	ChannelID pgtype.UUID        `json:"channel_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	LastRead  pgtype.UUID        `json:"last_read"`
}

type Message struct {
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Content   string             `json:"content"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	MsgType   pgtype.Text        `json:"msg_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
