// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) error
	EditMessage(ctx context.Context, arg EditMessageParams) (Message, error)
	EditWorkspace(ctx context.Context, arg EditWorkspaceParams) (Workspace, error)
	GenerateWorkspaceInvite(ctx context.Context, arg GenerateWorkspaceInviteParams) (GenerateWorkspaceInviteRow, error)
	GetChannelById(ctx context.Context, id pgtype.UUID) (Channel, error)
	GetChannelMembers(ctx context.Context, channelID pgtype.UUID) ([]GetChannelMembersRow, error)
	GetChannelMessages(ctx context.Context, arg GetChannelMessagesParams) ([]GetChannelMessagesRow, error)
	GetChannels(ctx context.Context) ([]Channel, error)
	GetChannelsByWorkspace(ctx context.Context, arg GetChannelsByWorkspaceParams) ([]Channel, error)
	GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error)
	GetThreadMessages(ctx context.Context, threadID pgtype.UUID) ([]GetThreadMessagesRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUserId(ctx context.Context, id pgtype.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error)
	GetWorkspaceByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]GetWorkspaceMembersRow, error)
	GetWorkspacesByUser(ctx context.Context, userID pgtype.UUID) ([]Workspace, error)
	IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error)
	IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error)
	JoinChannel(ctx context.Context, arg JoinChannelParams) error
	LeaveChannel(ctx context.Context, arg LeaveChannelParams) error
	SearchWorkspaces(ctx context.Context, arg SearchWorkspacesParams) ([]Workspace, error)
}

var _ Querier = (*Queries)(nil)
