// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug, is_private , created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, is_private, invite_code, invite_expires_at, created_by, created_at
`

type CreateWorkspaceParams struct {
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	IsPrivate bool        `json:"is_private"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Name,
		arg.Slug,
		arg.IsPrivate,
		arg.CreatedBy,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsPrivate,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE From workspaces
WHERE id = $1 and created_by = $2
`

type DeleteWorkspaceParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, arg.ID, arg.CreatedBy)
	return err
}

const editWorkspace = `-- name: EditWorkspace :one
UPDATE workspaces
set name = $1, slug = $2, is_private = $3
where id = $4 and created_by = $5
returning id, name, slug, is_private, invite_code, invite_expires_at, created_by, created_at
`

type EditWorkspaceParams struct {
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	IsPrivate bool        `json:"is_private"`
	ID        pgtype.UUID `json:"id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) EditWorkspace(ctx context.Context, arg EditWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, editWorkspace,
		arg.Name,
		arg.Slug,
		arg.IsPrivate,
		arg.ID,
		arg.CreatedBy,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsPrivate,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const generateWorkspaceInvite = `-- name: GenerateWorkspaceInvite :one
UPDATE workspaces
set 
    invite_code = $1,
    invite_expires_at = $2
where 
    id = $3
    and created_by = $4
returning invite_code, invite_expires_at
`

type GenerateWorkspaceInviteParams struct {
	InviteCode      pgtype.Text        `json:"invite_code"`
	InviteExpiresAt pgtype.Timestamptz `json:"invite_expires_at"`
	ID              pgtype.UUID        `json:"id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
}

type GenerateWorkspaceInviteRow struct {
	InviteCode      pgtype.Text        `json:"invite_code"`
	InviteExpiresAt pgtype.Timestamptz `json:"invite_expires_at"`
}

func (q *Queries) GenerateWorkspaceInvite(ctx context.Context, arg GenerateWorkspaceInviteParams) (GenerateWorkspaceInviteRow, error) {
	row := q.db.QueryRow(ctx, generateWorkspaceInvite,
		arg.InviteCode,
		arg.InviteExpiresAt,
		arg.ID,
		arg.CreatedBy,
	)
	var i GenerateWorkspaceInviteRow
	err := row.Scan(&i.InviteCode, &i.InviteExpiresAt)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, is_private, invite_code, invite_expires_at, created_by, created_at FROM workspaces WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsPrivate,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByInviteCode = `-- name: GetWorkspaceByInviteCode :one
SELECT id, name, slug, is_private, invite_code, invite_expires_at, created_by, created_at From
    workspaces
WHERE 
    invite_code = $1
    AND
    (
      invite_expires_at IS NULL
      OR invite_expires_at > NOW()
  )
`

func (q *Queries) GetWorkspaceByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByInviteCode, inviteCode)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsPrivate,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, is_private, invite_code, invite_expires_at, created_by, created_at FROM workspaces WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsPrivate,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMembers = `-- name: GetWorkspaceMembers :many
SELECT u.id,u.username,u.email,u.avatar_url,ws.role
FROM workspace_members ws
JOIN users u ON u.id = ws.user_id
where ws.workspace_id = $1
`

type GetWorkspaceMembersRow struct {
	ID        pgtype.UUID `json:"id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Role      string      `json:"role"`
}

func (q *Queries) GetWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]GetWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceMembersRow
	for rows.Next() {
		var i GetWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.AvatarUrl,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspacesByUser = `-- name: GetWorkspacesByUser :many
SELECT w.id, w.name, w.slug, w.is_private, w.invite_code, w.invite_expires_at, w.created_by, w.created_at FROM workspaces w
INNER JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1
ORDER BY w.created_at ASC
`

func (q *Queries) GetWorkspacesByUser(ctx context.Context, userID pgtype.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsPrivate,
			&i.InviteCode,
			&i.InviteExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isWorkspaceMember = `-- name: IsWorkspaceMember :one
SELECT EXISTS (
    SELECT 1 FROM workspace_members
    WHERE workspace_id = $1 AND user_id = $2
) AS is_member
`

type IsWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const searchWorkspaces = `-- name: SearchWorkspaces :many
SELECT id, name, slug, is_private, invite_code, invite_expires_at, created_by, created_at
FROM workspaces
WHERE
    (
        $1::text = ''
        OR name ILIKE '%' || $1::text || '%'
        OR slug ILIKE '%' || $1::text || '%'
    )
    AND (
        $2::uuid IS NULL
        OR created_by = $2::uuid
    )
    AND (
        $3::timestamptz IS NULL
        OR created_at >= $3::timestamptz
    )
    AND (
        $4::timestamptz IS NULL
        OR created_at < $4::timestamptz
    )
ORDER BY created_at DESC
LIMIT $6::int
OFFSET $5::int
`

type SearchWorkspacesParams struct {
	Search        string             `json:"search"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAfter  pgtype.Timestamptz `json:"created_after"`
	CreatedBefore pgtype.Timestamptz `json:"created_before"`
	PageOffset    int32              `json:"page_offset"`
	PageLimit     int32              `json:"page_limit"`
}

func (q *Queries) SearchWorkspaces(ctx context.Context, arg SearchWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, searchWorkspaces,
		arg.Search,
		arg.CreatedBy,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsPrivate,
			&i.InviteCode,
			&i.InviteExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
