/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceIdIndexRouteImport } from './routes/workspace/$id/index'
import { Route as WorkspaceDmUserIdRouteImport } from './routes/workspace/dm/$userId'
import { Route as WorkspaceChannelIdIndexRouteImport } from './routes/workspace/channel/$id/index'
import { Route as WorkspaceChannelIdThreadThreadIDIndexRouteImport } from './routes/workspace/channel/$id/thread/$threadID/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: '/workspace/$id/',
  path: '/workspace/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDmUserIdRoute = WorkspaceDmUserIdRouteImport.update({
  id: '/workspace/dm/$userId',
  path: '/workspace/dm/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceChannelIdIndexRoute = WorkspaceChannelIdIndexRouteImport.update({
  id: '/workspace/channel/$id/',
  path: '/workspace/channel/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceChannelIdThreadThreadIDIndexRoute =
  WorkspaceChannelIdThreadThreadIDIndexRouteImport.update({
    id: '/workspace/channel/$id/thread/$threadID/',
    path: '/workspace/channel/$id/thread/$threadID/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/dm/$userId': typeof WorkspaceDmUserIdRoute
  '/workspace/$id/': typeof WorkspaceIdIndexRoute
  '/workspace/channel/$id/': typeof WorkspaceChannelIdIndexRoute
  '/workspace/channel/$id/thread/$threadID/': typeof WorkspaceChannelIdThreadThreadIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/dm/$userId': typeof WorkspaceDmUserIdRoute
  '/workspace/$id': typeof WorkspaceIdIndexRoute
  '/workspace/channel/$id': typeof WorkspaceChannelIdIndexRoute
  '/workspace/channel/$id/thread/$threadID': typeof WorkspaceChannelIdThreadThreadIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/dm/$userId': typeof WorkspaceDmUserIdRoute
  '/workspace/$id/': typeof WorkspaceIdIndexRoute
  '/workspace/channel/$id/': typeof WorkspaceChannelIdIndexRoute
  '/workspace/channel/$id/thread/$threadID/': typeof WorkspaceChannelIdThreadThreadIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/workspace/'
    | '/workspace/dm/$userId'
    | '/workspace/$id/'
    | '/workspace/channel/$id/'
    | '/workspace/channel/$id/thread/$threadID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/workspace'
    | '/workspace/dm/$userId'
    | '/workspace/$id'
    | '/workspace/channel/$id'
    | '/workspace/channel/$id/thread/$threadID'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/workspace/'
    | '/workspace/dm/$userId'
    | '/workspace/$id/'
    | '/workspace/channel/$id/'
    | '/workspace/channel/$id/thread/$threadID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceDmUserIdRoute: typeof WorkspaceDmUserIdRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
  WorkspaceChannelIdIndexRoute: typeof WorkspaceChannelIdIndexRoute
  WorkspaceChannelIdThreadThreadIDIndexRoute: typeof WorkspaceChannelIdThreadThreadIDIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id/': {
      id: '/workspace/$id/'
      path: '/workspace/$id'
      fullPath: '/workspace/$id/'
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/dm/$userId': {
      id: '/workspace/dm/$userId'
      path: '/workspace/dm/$userId'
      fullPath: '/workspace/dm/$userId'
      preLoaderRoute: typeof WorkspaceDmUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/channel/$id/': {
      id: '/workspace/channel/$id/'
      path: '/workspace/channel/$id'
      fullPath: '/workspace/channel/$id/'
      preLoaderRoute: typeof WorkspaceChannelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/channel/$id/thread/$threadID/': {
      id: '/workspace/channel/$id/thread/$threadID/'
      path: '/workspace/channel/$id/thread/$threadID'
      fullPath: '/workspace/channel/$id/thread/$threadID/'
      preLoaderRoute: typeof WorkspaceChannelIdThreadThreadIDIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceDmUserIdRoute: WorkspaceDmUserIdRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
  WorkspaceChannelIdIndexRoute: WorkspaceChannelIdIndexRoute,
  WorkspaceChannelIdThreadThreadIDIndexRoute:
    WorkspaceChannelIdThreadThreadIDIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
