/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceCreateRouteImport } from './routes/workspace/create'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/workspace/$slug/index'
import { Route as WorkspaceSlugDmUserIdRouteImport } from './routes/workspace/$slug/dm/$userId'
import { Route as WorkspaceChannelIdIndexRouteImport } from './routes/workspace/channel/$id/index'
import { Route as WorkspaceChannelIdThreadThreadIDIndexRouteImport } from './routes/workspace/channel/$id/thread/$threadID/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceCreateRoute = WorkspaceCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSlugDmUserIdRoute = WorkspaceSlugDmUserIdRouteImport.update({
  id: '/$slug/dm/$userId',
  path: '/$slug/dm/$userId',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceChannelIdIndexRoute = WorkspaceChannelIdIndexRouteImport.update({
  id: '/channel/$id/',
  path: '/channel/$id/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceChannelIdThreadThreadIDIndexRoute =
  WorkspaceChannelIdThreadThreadIDIndexRouteImport.update({
    id: '/channel/$id/thread/$threadID/',
    path: '/channel/$id/thread/$threadID/',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/dm/$userId': typeof WorkspaceSlugDmUserIdRoute
  '/workspace/channel/$id/': typeof WorkspaceChannelIdIndexRoute
  '/workspace/channel/$id/thread/$threadID/': typeof WorkspaceChannelIdThreadThreadIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/$slug': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/dm/$userId': typeof WorkspaceSlugDmUserIdRoute
  '/workspace/channel/$id': typeof WorkspaceChannelIdIndexRoute
  '/workspace/channel/$id/thread/$threadID': typeof WorkspaceChannelIdThreadThreadIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/dm/$userId': typeof WorkspaceSlugDmUserIdRoute
  '/workspace/channel/$id/': typeof WorkspaceChannelIdIndexRoute
  '/workspace/channel/$id/thread/$threadID/': typeof WorkspaceChannelIdThreadThreadIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/login'
    | '/register'
    | '/workspace/create'
    | '/workspace/'
    | '/workspace/$slug/'
    | '/workspace/$slug/dm/$userId'
    | '/workspace/channel/$id/'
    | '/workspace/channel/$id/thread/$threadID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/workspace/create'
    | '/workspace'
    | '/workspace/$slug'
    | '/workspace/$slug/dm/$userId'
    | '/workspace/channel/$id'
    | '/workspace/channel/$id/thread/$threadID'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/workspace/create'
    | '/workspace/'
    | '/workspace/$slug/'
    | '/workspace/$slug/dm/$userId'
    | '/workspace/channel/$id/'
    | '/workspace/channel/$id/thread/$threadID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/create': {
      id: '/workspace/create'
      path: '/create'
      fullPath: '/workspace/create'
      preLoaderRoute: typeof WorkspaceCreateRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/$slug/': {
      id: '/workspace/$slug/'
      path: '/$slug'
      fullPath: '/workspace/$slug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/$slug/dm/$userId': {
      id: '/workspace/$slug/dm/$userId'
      path: '/$slug/dm/$userId'
      fullPath: '/workspace/$slug/dm/$userId'
      preLoaderRoute: typeof WorkspaceSlugDmUserIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/channel/$id/': {
      id: '/workspace/channel/$id/'
      path: '/channel/$id'
      fullPath: '/workspace/channel/$id/'
      preLoaderRoute: typeof WorkspaceChannelIdIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/channel/$id/thread/$threadID/': {
      id: '/workspace/channel/$id/thread/$threadID/'
      path: '/channel/$id/thread/$threadID'
      fullPath: '/workspace/channel/$id/thread/$threadID/'
      preLoaderRoute: typeof WorkspaceChannelIdThreadThreadIDIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceCreateRoute: typeof WorkspaceCreateRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugDmUserIdRoute: typeof WorkspaceSlugDmUserIdRoute
  WorkspaceChannelIdIndexRoute: typeof WorkspaceChannelIdIndexRoute
  WorkspaceChannelIdThreadThreadIDIndexRoute: typeof WorkspaceChannelIdThreadThreadIDIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceCreateRoute: WorkspaceCreateRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugDmUserIdRoute: WorkspaceSlugDmUserIdRoute,
  WorkspaceChannelIdIndexRoute: WorkspaceChannelIdIndexRoute,
  WorkspaceChannelIdThreadThreadIDIndexRoute:
    WorkspaceChannelIdThreadThreadIDIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
